- name: rocon_interactions/rviz.xml
    role: 'PC'
          compatibility: rocon:/pc/*/hydro|indigo/*
                display_name: Rviz Markers (Launcher)
                      description: Rviz with a view exactly configured for the rocon_interactions tutorial.
                            max: -1
                                  icon:
                                          resource_name: rocon_bubble_icons/rviz.png
- name: http://robotics-in-concert.github.io/rocon_tools/js/current/listener.html
    role: 'Web Apps'
          compatibility: rocon:/*/*/hydro|indigo
                display_name: Listener
                      description: Simple listener using rosjs in a web app.
                            icon:
                                    resource_name: rocon_bubble_icons/chimek.png
                                          parameters: 
                                                  rosbridge_address: __ROSBRIDGE_ADDRESS__
                                                          rosbridge_port: __ROSBRIDGE_PORT__
                                                                remappings:
                                                                        - remap_from: /chatter
                                                                                remap_to: /babbler
